service: tramline
image: ghcr.io/tramlinehq/tramline-web

builder:
  arch: amd64
  dockerfile: web.Dockerfile
  cache:
    type: gha
    options: mode=max
    image: app-build-cache
  # remote: ssh://sam-staging-local@35.209.23.61:22
  local: true
  secrets:
    - SSH_PRIVATE_KEY
    - RAILS_MASTER_KEY
    - KAMAL_REGISTRY_USERNAME
    - KAMAL_REGISTRY_PASSWORD

servers:
  web:
    hosts:
      - 35.209.23.61
    cmd: bundle exec puma -C config/puma.rb
  worker:
    hosts:
      - 35.209.23.61
    cmd: bundle exec sidekiq

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: sam-staging-local
  key_data: [$SSH_PRIVATE_KEY]

proxy:
  app_port: 3000
  healthcheck:
    interval: 5
    timeout: 5

deploy_timeout: 150
readiness_delay: 15

env:
  secret:
    - RAILS_MASTER_KEY
    - REDIS_URL
    - SSH_PRIVATE_KEY
    - KAMAL_REGISTRY_PASSWORD
    - DESCOPE_PROJECT_ID
    - DESCOPE_MANAGEMENT_KEY
    - KAMAL_REGISTRY_USERNAME
    - ANONYMIZE_SOURCE_DB_HOST
    - ANONYMIZE_SOURCE_DB_NAME
    - ANONYMIZE_SOURCE_DB_PASSWORD
    - ANONYMIZE_SOURCE_DB_USER
    - DEFAULT_REDIS_URL
    - SESSION_REDIS_URL
    - SIDEKIQ_REDIS_URL
    - APP_REDIRECT_MAPPING_JSON
    - HOST_NAME
    - SESSION_TIMEOUT_IN_MINUTES
    - SIDEKIQ_CONCURRENCY
    - SIDEKIQ_TIMEOUT
    - BILLING_URL
    - APPLELINK_URL
    - INTERCOM_APP_ID
    - JUNE_ANALYTICS_KEY
    - SENTRY_DSN
    - FRONTEND_SENTRY_DSN
    - SENTRY_SECURITY_HEADER_ENDPOINT
    - DISALLOWED_SIGN_UP_DOMAINS
    - CSP_REPORT_ONLY
    - CSP_CONNECT_SRC_URIS
    - DESCOPE_MANAGEMENT_KEY
    - DESCOPE_PROJECT_ID
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    - DATABASE_URL
  clear:
    RAILS_ENV: production
    RAILS_PIPELINE_ENV: staging

accessories:
  db:
    image: postgres:14
    host: 35.209.23.61
    port: "5432:5432"
    env:
      secret:
        - ANONYMIZE_SOURCE_DB_PASSWORD
        - ANONYMIZE_SOURCE_DB_USER
        - ANONYMIZE_SOURCE_DB_NAME
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
    directories:
      - data:/var/lib/postgresql/data
    options:
      restart: always

  redis:
    image: redis:7
    host: 35.209.23.61
    port: "6379:6379"
    directories:
      - data:/data
    options:
      restart: always
