name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install additional dependencies
        run: sudo apt-get update && sudo apt-get install -y libvips

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Generate a valid CycloneDX BOM
        run: |
          gem install cyclonedx-ruby
          wget https://github.com/CycloneDX/cyclonedx-cli/releases/latest/download/cyclonedx-linux-x64 -O cyclonedx-cli
          chmod +x cyclonedx-cli

          cyclonedx-ruby -p . -o sbom.xml
          ./cyclonedx-cli validate --input-file sbom.xml --fail-on-errors

      - name: Upload CycloneDX BOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: |
            sbom.xml
          retention-days: 7

      - name: Security bundler audit dependencies
        run: bundle exec bundler-audit --update

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager -w2

  lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
      redis:
        image: redis:alpine
        ports: [ "6379:6379" ]
        options: --entrypoint redis-server
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install additional dependencies
        run: sudo apt-get update && sudo apt-get install -y libvips

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint Ruby files
        run: bin/rubocop -f github

      - name: Lint ERB files
        run: bin/erb_lint --format compact --lint-all

      - name: Set up database schema integrity
        run: bin/rails db:schema:load

      - name: Check auto-loading
        run: bundle exec rails zeitwerk:check

  test:
    runs-on: ${{ github.ref != 'refs/heads/main' && 'warp-ubuntu-latest-x64-16x' || 'ubuntu-latest' }}
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
      redis:
        image: redis:alpine
        ports: [ "6379:6379" ]
        options: --entrypoint redis-server
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
      WORKERS: ${{ github.ref != 'refs/heads/main' && '8' || '4' }}
      DEFAULT_REDIS_URL: redis://localhost:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install additional dependencies
        run: sudo apt-get update && sudo apt-get install -y libvips

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Run asset pre compilation
        run: bundle exec rails assets:precompile

      - name: Setup Parallel Rspec DBs
        run: bundle exec rake db:parallel:create db:parallel:prepare

      - name: Run tests
        run: bundle exec rake parallel_rspec
